import Foundation

// Builds character-bigram models for non-Latin languages from Hunspell .dic
// files and emits Sources/LanguageModels.swift.
//
//   swift gen_models.swift <out.swift> he=/tmp/dics/he.dic ru=/tmp/dics/ru.dic …
//
// Each .dic is one word (stem) per line, optionally "word/affixflags". We keep
// the non-Latin letters of each word, count letter→letter transitions (with a
// boundary marker and Laplace smoothing), and calibrate a score threshold by
// comparing real words against random strings from the same alphabet.

let args = CommandLine.arguments
guard args.count >= 3 else { fatalError("usage: gen_models.swift <out> code=path …") }
let outPath = args[1]
let inputs: [(String, String)] = args[2...].map {
    let p = $0.split(separator: "=", maxSplits: 1); return (String(p[0]), String(p[1]))
}

func isLatin(_ c: Character) -> Bool {
    guard let u = Character(c.lowercased()).unicodeScalars.first?.value else { return false }
    return u >= 0x61 && u <= 0x7A
}

struct Model { let alphabet: String; let logProb: [Double]; let high, low, threshold: Double }

func build(_ path: String) -> Model? {
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else {
        FileHandle.standardError.write("  ! could not read \(path)\n".data(using: .utf8)!); return nil
    }
    var words: [String] = []
    var alpha = Set<Character>()
    for line in text.split(separator: "\n") {
        let raw = line.split(separator: "/").first.map(String.init) ?? String(line)
        let w = String(raw.lowercased().filter { $0.isLetter && !isLatin($0) })
        if w.count >= 2 { words.append(w); for c in w { alpha.insert(c) } }
    }
    guard words.count > 500, !alpha.isEmpty else { return nil }

    let alphabet = String(alpha.sorted())
    var index: [Character: Int] = [:]
    for (i, c) in Array(alphabet).enumerated() { index[c] = i }
    let n = alphabet.count + 1, boundary = alphabet.count
    var counts = Array(repeating: 5.0, count: n * n)
    for w in words {
        var prev = boundary
        for c in w { guard let cur = index[c] else { continue }; counts[prev * n + cur] += 1; prev = cur }
        counts[prev * n + boundary] += 1
    }
    var logProb = Array(repeating: 0.0, count: n * n)
    for i in 0..<n {
        var sum = 0.0; for j in 0..<n { sum += counts[i * n + j] }
        for j in 0..<n { logProb[i * n + j] = log(counts[i * n + j] / sum) }
    }
    func score(_ w: String) -> Double {
        var prev = boundary, s = 0.0, c = 0
        for ch in w { let cur = index[ch] ?? boundary; s += logProb[prev * n + cur]; c += 1; prev = cur }
        s += logProb[prev * n + boundary]; c += 1
        return c == 0 ? 0 : exp(s / Double(c))
    }
    let good = words.shuffled().prefix(8000).map(score).sorted()
    let chars = Array(alphabet)
    let bad = (0..<3000).map { _ -> Double in
        score(String((0..<Int.random(in: 3...8)).map { _ in chars.randomElement()! }))
    }.sorted()
    func pct(_ a: [Double], _ q: Double) -> Double {
        a.isEmpty ? 0 : a[min(a.count - 1, max(0, Int(Double(a.count - 1) * q)))]
    }
    let high = pct(good, 0.10), low = pct(bad, 0.90)
    FileHandle.standardError.write("  \(alphabet.count) letters, \(words.count) words\n".data(using: .utf8)!)
    return Model(alphabet: alphabet, logProb: logProb, high: high, low: low, threshold: (high + low) / 2)
}

var out = "// Auto-generated by tools/gen_models.swift — do not edit by hand.\n"
out += "// Character-bigram (Markov) models for non-Latin languages, built from\n"
out += "// Hunspell dictionaries. English is trained at runtime; see GibberishDetector.\n\n"
out += "enum LanguageModelData {\n"
out += "    struct Entry { let alphabet: String; let anchorHigh, anchorLow, threshold: Double; let logProb: [Double] }\n\n"
out += "    static let byLang: [String: Entry] = [\n"
for (code, path) in inputs {
    FileHandle.standardError.write("\(code): \(path)\n".data(using: .utf8)!)
    guard let m = build(path) else { continue }
    let lp = m.logProb.map { String(format: "%.4f", $0) }.joined(separator: ", ")
    out += "        \"\(code)\": Entry(alphabet: \"\(m.alphabet)\", "
    out += "anchorHigh: \(m.high), anchorLow: \(m.low), threshold: \(m.threshold),\n"
    out += "            logProb: [\(lp)]),\n"
}
out += "    ]\n}\n"
try out.write(toFile: outPath, atomically: true, encoding: .utf8)
print("Wrote \(outPath)")
